# Muda o prefixo de Ctrl+b para Ctrl+a (como o GNU Screen)
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Exibe hora e data na barra inferior
set -g status-right "📅 %Y-%m-%d 🕒 %H:%M"

# Cor da barra
set-option -g status-position top
set -g status-bg colour235
set -g status-fg colour136
set -g status-left-length 30
set -g status-right-length 100

# Fechar abas com "X"
bind x confirm-before -p "Fechar este painel? (y/n)" kill-pane

# Movimentar entre painéis com "Alta + Setas"
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Dividir janelas com atalhos simples
bind | split-window -h     # Divide verticalmente
bind - split-window -v     # Divide horizontalmente

# Numerar janelas a partir do 1
set -g base-index 1
setw -g pane-base-index 1

# Limpar a tela com Ctrl+l
bind C-l send-keys 'C-l'

# Habilitar suporte ao mouse
set -g mouse on

# Navegar entre sessões
bind p previous-session   # Ctrl+a p
bind n next-session       # Ctrl+a n
bind s choose-session     # Ctrl+a s: lista e permite selecionar sessões

# Criar nova sessão
bind c new-session

# Renomear sessão atual
bind r command-prompt -I "#S" "rename-session '%%'"

# Desanexar da sessão atual
bind d detach-client

